### ISSUE TITLE
Illustrative test datasets

### ISSUE THREAD

**Issue by arteys** [mehta-lab/VisCy#101]
Hi. Really want to try virtual staining, however I can't find Illustrative test datasets mentioned in the article in this repository. Am I missing something?

**Comment by ziw-liu** [comment]
Hi @arteys and thanks for your interest! We did upload the test dataset earlier to a public web server. However due to a technical error, that archive was deleted, and we are now actively working on restoring access. We expect a fix very soon, and will update on this issue accordingly.

**Comment by ziw-liu** [comment]
The dataset hosting is restored at https://public.czbiohub.org/comp.micro/viscy/. Please refer to the updated example scripts (on the main branch).

**Comment by arteys** [comment]
Thank you very much. Do you mind if I ask stupid questions in case I don't get it all up and running?

**Comment by ziw-liu** [comment]
> Thank you very much. Do you mind if I ask stupid questions in case I don't get it all up and running?

No questions are stupid! We would appreciate your feedback.

**Comment by ziw-liu** [comment]
I assume all is going well. Feel free to open a new issue if you encounter problems.
