### ISSUE TITLE
document published models on Wiki

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/VisCy#117]
We should document the models and releases that match each preprint or paper we post. 
The page should describe how to run inference, and where appropriate, how to train the model.
Creating a "Model library" page in Wiki makes sense, with the following three sub-pages:
* robust virtual staining (inference + training): @ziw-liu 
* mantis (inference): @edyoshikun 
* ultrack (inference): @edyoshikun 
* 
Zenodo record you put together for mantis: https://zenodo.org/records/10403605 is a good template for what to share via these pages. And, the Wiki pages can go beyond and point to specific scripts in this or other repos.

**Comment by mattersoflight** [comment]
Zenodo record you put together for mantis: https://zenodo.org/records/10403605 is a good template for what to share via these pages. And, the Wiki pages can go beyond and point to specific scripts in the repo.

**Comment by ziw-liu** [comment]
We have opted to host the model weights as release artifacts because that allows for up to 2 GB file size. The wiki only allows 100 MB which is smaller than a single checkpoint file.

**Comment by ziw-liu** [comment]
Closed by #119.
