### ISSUE TITLE
Unify stem implementation

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/VisCy#120]
@ziw-liu I wrote the `StemDepthtoChannels` to work for resnet and convnext models. Can you test the construction of UNeXt2 model with this stem and report back if the construction works? If it does, we should deprecate other classes for building the stem to avoid confusion in the future.

_Originally posted by @mattersoflight in https://github.com/mehta-lab/VisCy/pull/113#discussion_r1699256341_

**Comment by ziw-liu** [comment]
https://github.com/mehta-lab/VisCy/pull/113/files#discussion_r1699256669

**Comment by mattersoflight** [comment]
Replacing `viscy.unet.networks.unext2.UNext2Stem` with `StemDepthtoChannels` will break the compatibility between the constructed model and checkpoints for the virtual staining task.
