### ISSUE TITLE
CLI for multiple training tasks

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/VisCy#127]
As part of #126, @ziw-liu suggested:  
> For the future iteration (v0.3?) it might make sense to replace the manual CLI entry point (viscy [command]) with python's built-in (python -m viscy.cli.module [command]) to make supporting multiple learning tasks easier.

This makes a lot of sense and I'd vote to make this change sooner to clarify that the repo does implement multiple learning tasks. It is easy to change our virtual training scripts that launch training from `viscy [command]` -> `python -m viscy.cli.module [command]`. Are there other factors for which we should wait to refactor CLI? 

@ziw-liu @edyoshikun

**Comment by ziw-liu** [comment]
I'd do it after v0.2.0 is released (i.e. after #114) so that the v0.1.0 API reported in various places is kept in the release.

**Comment by edyoshikun** [comment]
I am having trouble seeing what is the added benefit of using `python -m viscy.cli.module [command]`. What is this enabling? 
Also,  #114 does not rely on the CLI so you could change it now. I would prefer if you make the changes now and we update the wiki to the latest method of calling the training/prediction than having to change this twice. The instructions will be on [the wiki ](https://github.com/mehta-lab/VisCy/wiki/virtual-staining-instructions).

**Comment by edyoshikun** [comment]
I merged #114. @ziw-liu feel free to make the changes

**Comment by mattersoflight** [comment]
@ziw-liu The change in CLI and the refactor of modules that implement multiple learning tasks can be done in a single PR.
