### ISSUE TITLE
Model size mismatch error during prediction

### ISSUE THREAD

**Issue by Soorya19Pradeep** [mehta-lab/VisCy#134]
There is a stem size mismatch error when running the prediction. I have trained the model using the phase images only.
You can find my training config here:
`/hpc/projects/comp.micro/infected_cell_imaging/Single_cell_phenotyping/code_testing_soorya/fit.yml`
Prediction config is here:
`/hpc/projects/comp.micro/infected_cell_imaging/Single_cell_phenotyping/code_testing_soorya/output/predict/predict.yml`
The slurm output is here:
`/hpc/projects/comp.micro/infected_cell_imaging/Single_cell_phenotyping/code_testing_soorya/output/predict/slurm-15752038.out`

If required the training output including the checkpoints are here:
`/hpc/projects/comp.micro/infected_cell_imaging/Single_cell_phenotyping/code_testing_soorya/lightning_logs/vanilla_new/`

**Comment by mattersoflight** [comment]
@Soorya19Pradeep this error is likely due to a mismatch in the number of z-slices you specify during model construction. 

Your fit.yml has this config:

```
model:
  backbone: convnext_tiny
  in_channels: 1
  log_batches_per_epoch: 3
  log_samples_per_batch: 3
```

predict.yml:
```
model:
  backbone: convnext_tiny
  in_channels: 1
  in_stack_depth: 5
  stem_kernel_size: [5, 4, 4]
```

This means that your model was trained with 15 z-slices, which is the default in `ContrastiveModule`

```
class ContrastiveModule(LightningModule):
    """Contrastive Learning Model for self-supervised learning."""

    def __init__(
        self,
        backbone: str = "convnext_tiny",
        loss_function: Union[
            nn.Module, nn.CosineEmbeddingLoss, nn.TripletMarginLoss
        ] = nn.TripletMarginLoss(),
        margin: float = 0.5,
        lr: float = 1e-3,
        schedule: Literal["WarmupCosine", "Constant"] = "Constant",
        log_batches_per_epoch: int = 8,
        log_samples_per_batch: int = 1,
        in_channels: int = 1,
        example_input_yx_shape: Sequence[int] = (256, 256),
        in_stack_depth: int = 15,
        stem_kernel_size: tuple[int, int, int] = (5, 4, 4),
        embedding_len: int = 256,
        predict: bool = False,
        drop_path_rate: float = 0.2,
    ) -> None:
    
 ```
 
 If you don't override any the model construction parameters via config, they will be assigned like above. Deleting the `  in_stack_depth: 5` from predict.yml could resolve this.

**Comment by mattersoflight** [comment]
The channel dimensions are mismtached by a factor of 3 (96/32), matching the ratio of z-slices in two configs.

```
RuntimeError: Error(s) in loading state_dict for ContrastiveModule:
        size mismatch for model.stem.conv.weight: copying a param with shape torch.Size([32, 1, 5, 4, 4]) from checkpoint, the shape in current model is torch.Size([96, 1, 5, 4, 4]).
        size mismatch for model.stem.conv.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([96]).
  ```

**Comment by Soorya19Pradeep** [comment]
Thanks @mattersoflight ! Yes, it was due to the mismatch in the number of z slices. I corrected it and the predictions are running now.
