### ISSUE TITLE
Patches with cells not in center

### ISSUE THREAD

**Issue by Soorya19Pradeep** [mehta-lab/VisCy#142]
I find very few patches logged on TensorBoard which doesn't have a cell in the middle, but on the side.
<img width="248" alt="image" src="https://github.com/user-attachments/assets/111116b9-0314-481f-b4d1-1e41dbc54e2a">
Could this be an issue with how dataloader picks these patches, or from the segmentation?

The earlier point I made about cells at the boundary of the image is wrong. There are no such cells.

**Comment by ziw-liu** [comment]
@Soorya19Pradeep Do you have the index of some of these cells by any chance? This is most likely a VS/tracking error.

**Comment by Soorya19Pradeep** [comment]
I don't @ziw-liu . But I am wondering if these are the background points we are seeing in the umaps. I will look into those points.

**Comment by Soorya19Pradeep** [comment]
It seems like it can be misplaced segmentations from checking the patch around the labels. 
![image](https://github.com/user-attachments/assets/3e64c3a6-8ffd-48e8-b02b-78d41ecb913a)
![image](https://github.com/user-attachments/assets/752a9823-58f3-47f4-8cae-2fe467ad09df)
![image](https://github.com/user-attachments/assets/a560d811-d53c-4eb8-89ca-3949884956dc)
![image](https://github.com/user-attachments/assets/520ad468-1387-40b3-ae78-751357dc0cc6)
