### ISSUE TITLE
Store dimensionality reduction for feature visualization

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/VisCy#166]
> The speed of analysis will improve if we don't have to do the dimensionality reduction for each FOV.
https://github.com/czbiohub-sf/napari-iohub/pull/13#issuecomment-2352089033

**Comment by Soorya19Pradeep** [comment]
@ziw-liu, I think it is better to do it through script as the UMAP components will change with run as well as number of components.

**Comment by ziw-liu** [comment]
> UMAP components will change with run as well as number of components

The idea would be to store one UMAP per prediction run so it shouldn't change unless we need to tweak clustering parameters.

**Comment by Soorya19Pradeep** [comment]
Ok. It makes sense for the Napari plugin as it makes it faster. Storing the UMAP components makes sense for this.
