### ISSUE TITLE
Discussion of what metrics to prioritize in inference tensorboard

### ISSUE THREAD

**Issue by Christianfoley** [mehta-lab/VisCy#19]
Each time inference is run it generates a tensorboard output displaying the outputs of inference and metrics calculated along multiple orientations. Each scalar added (each sub-tag corresponding to a metric calculated) [generates a new folder in a recursive structure](https://github.com/pytorch/pytorch/issues/32651), resulting in potentially prohibitively long session load-times depending on the number and type of metrics you calculate.

Let's have a discussion here about:

1. What metrics have we implemented (@Soorya19Pradeep) and whether they are integrated into the inference module.
2. Which of these metrics should we prioritize supporting on inference calls.

**Comment by ziw-liu** [comment]
Closed by #21.
