### ISSUE TITLE
Augmentation strategy for mantis data

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/VisCy#23]
Label-free datasets acquired on the mantis have similar in-plane pixel size as hummingbird@63x, where a lot of the training data was acquired. To apply 2.5D virtual staining across microscopes, however, axial spatial augmentation is needed to match training data distribution (250 nm) to the wide range of existing (570 nm, https://github.com/czbiohub-sf/mantis/pull/69) and future (205 nm) Z-sampling on mantis.

@talonchandler suggests that trilinear is a good interpolation to start with (0.4x to 1.2x scaling in Z). We will also investigate the unit of voxel intensity values in the reconstructed phase images, since mantis has a different illumination wavelength (450 nm) than hummingbird (532 nm).

Pinging @Soorya19Pradeep and @edyoshikun in case these numbers are not accurate.

**Comment by mattersoflight** [comment]
@ziw-liu  thanks for starting this discussion on axial spatial augmentation. 

> We will also investigate the unit of voxel intensity values in the reconstructed phase images, since mantis has a different illumination wavelength (450 nm) than hummingbird (532 nm).

Examining the XY and XZ cross sections of the phase and fluorescence volumes from both microscopes will be very informative. I look forward to that data. 

> For this scaling range and a 5-slice output, the input stack needs to be 11-slice.

I don't see images in your last comment, so I ran the snippet above, and see this: 
![image](https://github.com/mehta-lab/viscy/assets/2934183/aba76962-27b3-4c93-8f1a-9a0280437a30)

It does make sense that we read in more data to make sure that we don't have boundary artifacts. 

Some other comments:
* The training data acquired on hummingbird and test data from mantis has sufficient spatial resolution and sampling in z to capture the shape and texture of nuclei and membrane.  In other words, 205nm, 250nm, and 570nm are all sufficient sampling intervals to resolve nuclei and cell contours. 570nm sampling is likely insufficient for membrane.
* We will collect a lot of data on membrane with mantis.

**Comment by mattersoflight** [comment]
The solution to this issue is in progress.

 #26 and #27 were merged into the main to make it easy to install viscy from the main during the DL@MBL course. 
 
 @ziw-liu can you elaborate on #28? Should it be merged while testing the 2D UNet?

**Comment by ziw-liu** [comment]
> @ziw-liu can you elaborate on #28? Should it be merged while testing the 2D UNet?

Yes, that PR has 2 bug fixes.
