### ISSUE TITLE
draft demo dataset and notebook

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/VisCy#26]
**Dataset**
HEK293T cells with phase, membrane, and nuclei channels. Let's start with 50 FOVs.

**checkpoint 1** 
Load zarr store, view label-free and fluorescence channels, configure model, browse the 2D UNet with tensorboard, start a training a phase->nuclei model.

**checkpoint 2** 
 Examine loss after lunch, see the regression metrics for the phase->nuclei model, train nuclei->phase model, and see the regression metrics for the nuclei->phase model.

**checkpoint 3** 
Adjust the network capacity by different amounts and each student trains one model (phase -> nuclei, phase-> membrane, phase -> nuclei, membrane). Record the metrics on a Google doc.

**Comment by ziw-liu** [comment]
> HEK293T cells with phase, membrane, and nuclei channels. Let's start with 50 FOVs.

For a 2D network, should the phase reconstruction be 2D as well to boost contrast?

**Comment by ziw-liu** [comment]
Closing in favor of #82.
