### ISSUE TITLE
PSNR as a regression metric

### ISSUE THREAD

**Issue by ziw-liu** [mehta-lab/VisCy#33]
[PSNR](https://torchmetrics.readthedocs.io/en/stable/image/peak_signal_noise_ratio.html) is a commonly used metric to evaluate high-resolution features in image reconstruction problems such as [deconvolution](https://doi.org/10.1038/s41592-022-01652-7) and [natural image super-resolution](https://arxiv.org/pdf/1609.05158.pdf). This seems like a useful addition to MSE and SSIM that helps with resolution-sensitive tasks.

**Comment by ziw-liu** [comment]
On second thought, PSNR is just max over MSE, which may not be more informative than $r^2$ or SSIM.

**Comment by ziw-liu** [comment]
Paper comparing [PSNR and SSIM](https://www.researchgate.net/profile/Alain-Hore/publication/220931731_Image_quality_metrics_PSNR_vs_SSIM/links/55119e8e0cf270fd7e307c6a/Image-quality-metrics-PSNR-vs-SSIM.pdf). For SSIM ~ (0.2, 0.8) and similar luminance, there is a near-linear relation between the two metrics.

**Comment by mattersoflight** [comment]
Closing this since we are currently using SSIM.
