### ISSUE TITLE
configurable augmentations

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/VisCy#55]
A key hyperparameter of our training process is the choice of augmentations. At this point, the augmentations are hard coded. @ziw-liu how can we make the augmentations configurable via pytorch lightning config? A useful side-effect is that augmentations that go into each computational experiment will be automatically documented.

**Comment by ziw-liu** [comment]
I think this is possible with dependency injection, the same way as we planned for the models in https://github.com/mehta-lab/VisCy/issues/42#issuecomment-1699525779.
