### ISSUE TITLE
VS predictions should output the correct voxel_size/scale

### ISSUE THREAD

**Issue by edyoshikun** [mehta-lab/VisCy#62]
One inconvenient step in the mantis analysis pipeline is having to go and remember to change the scale metadata on the virtually stained predictions. Is it possible to write the input dataset's scale as the output scale?

**Comment by ziw-liu** [comment]
It could be done. The reason why it was omitted is that the prediction writer is currently written as a subclass of the `lightning.pytorch.callbacks.BasePredictionWriter` callback. This means that all the information it receives at runtime comes from the batch. So the scale information would have to be packed into the batch data, which introduces a small GPU syncing overhead.

**Comment by ziw-liu** [comment]
Fixed in #89 and #93.
