### ISSUE TITLE
Implement test time augmentations to avoid high frequency fluctuations

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/VisCy#77]
With a variety of models, we see that virtually stained structures show high-frequency fluctuations over time. This may be due to the sensitivity of ConvNets to small changes in local texture and orientation of edges. One way to average over these effects is to do test time augmentation. Let's experiment with one of our trained models and compare the temporal consistency of predictions with and without test-time augmentations.

Relevant paper: https://www.nature.com/articles/s41598-020-61808-3

**Comment by ziw-liu** [comment]
Closed by #91.
