### ISSUE TITLE
image translation exercise for DL@MBL

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/VisCy#82]
The students will program a UNet near the start of the course and we have scheduled image translation after segmentation and denoising exercises. We have a 6-hour window for this exercise, which will be divided between deterministic image translation and generative image translation.  For deterministic image translation, we'd use UNeXt2 architecture, and for generative translation we'll probably use [conditional GAN](https://tcwang0509.github.io/pix2pixHD/) used in [this paper ](https://ieeexplore.ieee.org/document/10230501).

Considering the above plan and the need for a demo notebook for release 0.2.0 of VisCy, I suggest that we develop a demo notebook that illustrate the training of the VSCyto3D and VSNeuromast models.

Here are Alishba's fixes to last year's exercise:
https://github.com/alishbaimran/image_translation/blob/solution/solution.ipynb
https://docs.google.com/document/d/1h3u42hodHN7nQz9qND-NQc7uOm72fBi7DxURNYuuYPM/edit

**Comment by edyoshikun** [comment]
For the release, we will add some prediction notebooks first included in #94.
We will iterate on the DL@MBL notebooks afterward.

**Comment by edyoshikun** [comment]
#114 Closes this issue
