### ISSUE TITLE
Normalization for patches ome-zarr

### ISSUE THREAD

**Issue by alishbaimran** [mehta-lab/VisCy#97]
We want to compute statistics from the FOV-scale zarr store and store it with patch-scale zarr store, which dataloader will parse. 

The process for this is:
- Compute statistics per FOV (not patch) and store these with metadata.
- Normalize using FOV statistics at training and test time - use existing CLI or preprocessing script.

This is current structure of the patches ome_zarr:

=== Summary ===
Format:                  omezarr v0.4
Axes:                    T (time); C (channel); Z (space); Y (space); X (space);
Channel names:           ['RFP', 'Phase3D']
Row names:               ['A', 'B']
Column names:            ['3', '4']
Wells:                   4
Positions:               2629

![image](https://github.com/mehta-lab/VisCy/assets/44557946/6a66c4d4-7e3b-46d9-b019-f96ce67d3d2c)
![image](https://github.com/mehta-lab/VisCy/assets/44557946/3dbf0d18-ea1b-4120-b732-e1f4d6d99469)

This is structure of track_labels zarr where we can store the meta data: (fov information can be stored here)
=== Summary ===
Format:                  omezarr v0.4
Axes:                    T (time); C (channel); Z (space); Y (space); X (space); 
Channel names:           ['tracking']
Row names:               ['A', 'B']
Column names:            ['3', '4']
Wells:                   4
Positions:               61

<img width="448" alt="Screenshot 2024-06-28 at 10 00 40 AM" src="https://github.com/mehta-lab/VisCy/assets/44557946/e62fbd6b-1cff-4138-aeb7-00d98585c998">

Need help on how to integrate metadata into the track ome_zarr, how this will be used to generate the patch ome_zarr and then eventually the dataloader for normalization.

**Comment by mattersoflight** [comment]
> Need help on how to integrate metadata into the track ome_zarr, how this will be used to generate the patch ome_zarr and then eventually the dataloader for normalization.

@alishbaimran our initial approach can be
* compute FOV statistics from `track_labels.zarr/row/col/fovN/` array.
* write them to each cropped FOV in `patches.zarr` in `/row/col/fovNcellM/.zattr` file. 
* use the statistics while loading patches for normalizing the data.

**Comment by ziw-liu** [comment]
Now obsolete since we removed patchification.
